//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalLims.Main
{


    public partial class InPatWalkInDash
    {

        /// <summary>
        /// DataCountRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater DataCountRepeater;

        /// <summary>
        /// InPatTimeLineGraph control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InternalLims.Main.uc.InPatTimeLineGraph InPatTimeLineGraph;

        /// <summary>
        /// InPatPaymentTypeDonut control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InternalLims.Main.uc.InPatPaymentTypeDonut InPatPaymentTypeDonut;
    }
}
